# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5d139d6fc5bd00cd5d89f22f0aead691a789e83ff2d4de3bce23b42394d0b16e31dac783ecc751544fa4960c3d5d80225944ebca8bfa1c4877d29e8b000d420

test:
  secret_key_base: bc903687fa9d1ad2ecbf21eb466909dccac7357f170b41a642b510c6cd8732facf14d6c640f6fbd805d6fddebe33fae128440ea6bfa556b859f6d8d3fecc75f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
